### ISSUE TITLE
[ICON REQUEST]

### ISSUE THREAD

**Issue by maxisme** [artcoholic/akar-icons#30]
**Describe the icon you'd like to be added**
A double check. In Material Icons it is called "done all".

**Sample icon**
![baseline_done_all_black_24dp](https://user-images.githubusercontent.com/16902919/113834700-0aa49400-9783-11eb-856e-b23c7159fd59.png)

**Comment by artcoholic** [comment]
@maxisme Thanks for the suggestion! It's been added to the library.

**Comment by maxisme** [comment]
Amazing, Thank you so much!

**Comment by maxisme** [comment]
Hey, I have noticed this icons height is quite a lot smaller than the rest? Is that on purpose? Thank you
<img width="559" alt="image" src="https://user-images.githubusercontent.com/16902919/118357516-7a702080-b572-11eb-84c1-30acbbe8484e.png">

**Comment by artcoholic** [comment]
Hi @maxisme! Yes, that is intentional because of the orientation of the icon. I follow a grid system when I built these icons, check out the screenshot below:
![Screenshot 2021-05-15 104354](https://user-images.githubusercontent.com/6734458/118373274-d040ca80-b56a-11eb-999f-cf35079c790c.png)

There is also a thing called optical alignment. If I start making all icons have the same size, the icons wouldn't be optically aligned. Check out this article https://medium.com/ringcentral-ux/eyeballing-or-optical-alignment-in-design-4ef5ab2d326f

**Comment by maxisme** [comment]
Ahh okay! Makes sense! Thanks
