### ISSUE TITLE
[ICON REQUEST] Additional chat bubble icons

### ISSUE THREAD

**Issue by vineetdigit** [artcoholic/akar-icons#57]
Akar provides some excellent chat bubble icons already. I want to request a few more icons as described below.

![image](https://user-images.githubusercontent.com/11036997/129620735-e660d13e-61d9-4020-b249-abf88be24820.png)

Are these possible? 

thanks!

Vineet

**Comment by artcoholic** [comment]
@vineetdigit Yeah this is doable. I Will let you know when it's added.

**Comment by vineetdigit** [comment]
Great! Thank you and appreciate it.

**Comment by artcoholic** [comment]
@vineetdigit I've added `chat-approve`, `chat-question`, and `chat-edit` per your request. I left out `approve and comment` and `reject and comment` because these can be achieved by using the `chat-approve` and `chat-error` icons. The person icon inside of these is a bit too detailed and doesn't fit in the small icon size. 

Let me know if you have any other suggestions. Thanks!

**Comment by vineetdigit** [comment]
Thanks for turning this around so quickly!

I was suspecting that the person icon would be difficult to put inside the
chat bubble. The rest of the icons look superb!

thanks again.

Vineet :-)
